import {
  Lock,
  MapPin,
  Ruler,
  Bed,
  Bath,
  MessageCircle,
  LayoutDashboard,
  Building2,
  TrendingUp,
  Search,
  Filter,
  Pencil,
  CheckCircle2,
  ChevronLeft,
  ChevronRight,
  Calendar,
  LogIn,
  Eye,
  EyeOff,
  Crosshair,
  Layers,
  Plus,
  Minus,
  Waves,
  Car,
  Shield,
  ShieldCheck,
  ArrowLeft,
  LogOut,
  type LucideIcon,
} from "lucide-react";

const iconMap = new Map<string, LucideIcon>([
  ["lock", Lock],
  ["location_on", MapPin],
  ["square_foot", Ruler],
  ["bed", Bed],
  ["bathtub", Bath],
  ["chat_bubble", MessageCircle],
  ["dashboard", LayoutDashboard],
  ["domain", Building2],
  ["trending_up", TrendingUp],
  ["search", Search],
  ["filter_list", Filter],
  ["edit", Pencil],
  ["check_circle", CheckCircle2],
  ["chevron_left", ChevronLeft],
  ["chevron_right", ChevronRight],
  ["calendar_today", Calendar],
  ["login", LogIn],
  ["visibility", Eye],
  ["visibility_off", EyeOff],
  ["my_location", Crosshair],
  ["layers", Layers],
  ["add", Plus],
  ["remove", Minus],
  ["pool", Waves],
  ["local_parking", Car],
  ["security", Shield],
  ["verified_user", ShieldCheck],
  ["arrow_back", ArrowLeft],
  ["logout", LogOut],
]);

export function getIcon(name: string): LucideIcon | undefined {
  return iconMap.get(name);
}


